# Generated by Django 5.1.7 on 2025-05-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(blank=True, choices=[('for_kids', 'For Kids'), ('for_men', 'For Men'), ('for_women', 'For women')], max_length=120, null=True),
        ),
    ]
